vscode:
  extensions:
    - eamodio.gitlens@10.2.0:L4GfuK5a2eOIpfcKVVvjEw==
    - ritwickdey.live-sass@3.0.0:x2c+sCJm+QmH2qn2h1X9Zw==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - Equinusocio.vsc-material-theme@32.4.0:eZWyxHJ/u8fYF+bEnk3JRA==
    - PKief.material-icon-theme@3.9.2:xeHlNzPEF04yFqz/xKCD5w==
    - thekalinga.bootstrap4-vscode@6.1.0:duaQhthWtxWBzXAGe+5GKQ==
    - esbenp.prettier-vscode@3.18.0:SpDMXXww8cAUOXaBCNECgQ==